import express from 'express';
import cors from 'cors';
import passport from './Infrastructure/Config/Passport';
import requestLogger from './Application/Middleware/RequestLogger';
import errorHandler from './Application/Middleware/ErrorHandler';
import MongoDB from './Infrastructure/Persistence/Config/MongoDB';
import swaggerSpec from './Infrastructure/Persistence/Config/Swagger';
import swaggerUi from 'swagger-ui-express';
import clothesRouter from './Application/Routes/ClothesRoutes';
MongoDB();
const app = express();
app.use(passport.initialize());
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({extended:true}));
app.use(requestLogger);
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));
app.get('/swagger.json', (req, res) => {
    res.setHeader('Content-Type', 'application/json');
    res.send(swaggerSpec);
});
app.use('/api', clothesRouter);
app.use(errorHandler);
export default app;